name: Contentstack iOS Delivery SDK Release

on:
  release:
    types:
      - created

jobs:
  release:
    name: Release Contentstack iOS Delivery SDK Release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version

      - name: Install dependencies
        run: |
          pod install --repo-update

      - name: Build
        run: |
          # Add commands to build and test your package
          xcodebuild -workspace Contentstack.xcworkspace -scheme 'Contentstack' -destination 'platform=iOS Simulator,name=iPhone 13 Pro'

      - name: CocoaPods trunk push
        run: pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}