name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cocoapods Dependencies
        run: |
          gem install cocoapods
          pod install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/cocoapods@v1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
